### PR TITLE
use lib instead of utils

### PR DESCRIPTION
**Pull request by DevX32**
## Description
noclip 360 issue fix, lib locale, and use lib instead of utils

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by DevX32** [comment]
@Manason

**Comment by MafewTM** [comment]
This is not just changing the utils module to the lib module. There is a lot more here which should be in separate PRs.

**Comment by BerkieBb** [comment]
Resolve conflicts

**Comment by DevX32** [comment]
done and conversion reverted lib to utils

**Review by solareon — APPROVED** [review]

**Review by MafewTM — APPROVED** [review]

**Pull request merged**
