### PR TITLE
Fixes for blips and names not showing

### PR DESCRIPTION
**Pull request by Molicheu**
## Description

This pull request
 fixes https://github.com/Qbox-project/qbx_adminmenu/issues/21
 
blips
names

## Checklist

- [ x ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ x ] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by MafewTM** [comment]
Besides adding all the unnecessary spaces, it looks good to me

**Comment by Molicheu** [comment]
> Besides adding all the unnecessary spaces, it looks good to me

My lua formatter did a horrible job

**Comment by MafewTM** [comment]
Should fix it up. Ill approve anyways tho

**Review by MafewTM — APPROVED** [review]

**Comment by dusan01** [comment]
I tested it, and it works fine, but for blips, it's always showing admin as a vehicle blip.

**Comment by D4isDAVID** [comment]
Would be nice if you remove all the formatting completely since this PR isn't supposed to be doing that

**Comment by Molicheu** [comment]
> Would be nice if you remove all the formatting completely since this PR isn't supposed to be doing that

Sure I can do that

**Comment by Molicheu** [comment]
> I tested it, and it works fine, but for blips, it's always showing admin as a vehicle blip.

Yeah I see that, not sure why, haven't checked that out yet

**Pull request merged**
