### PR TITLE
use txadmin noclip

### PR DESCRIPTION
**Pull request by DevX32**
## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by DevX32** [comment]
need to fix the noclip command searching for the txadmin event

**Comment by DevX32** [comment]
@Manason

**Comment by solareon** [comment]
So the issue I see with this one is does it work if you don't have txadmin perms to no clip? Some server owners/admins may not want to give txadmin permissions to folks hence the desire for an alternative noclip

**Comment by DevX32** [comment]
> So the issue I see with this one is does it work if you don't have txadmin perms to no clip? Some server owners/admins may not want to give txadmin permissions to folks hence the desire for an alternative noclip

but server owners can give only noclip access though i asked manason he said its good though

**Comment by DevX32** [comment]
i dont think there is diffrence between the tx noclip and normal admin one though

**Comment by MafewTM** [comment]
If this required server owners to add people to the cfg just for noclip access, I think we should stick with what we have already

**Comment by Manason** [comment]
Needs to be tested in a scenario where a non-owner admin without txAdmin access can noclip

**Comment by BerkieBb** [comment]
> If this required server owners to add people to the cfg just for noclip access, I think we should stick with what we have already

That doesn't make sense as we use the cfg for all our permissions too

**Comment by MafewTM** [comment]
> > If this required server owners to add people to the cfg just for noclip access, I think we should stick with what we have already
> 
> That doesn't make sense as we use the cfg for all our permissions too

It makes perfect sense. Why have to set another permission for someone when you can just set them as mod and it deals with noclip already.

**Comment by BerkieBb** [comment]
> > > If this required server owners to add people to the cfg just for noclip access, I think we should stick with what we have already
> > 
> > 
> > That doesn't make sense as we use the cfg for all our permissions too
> 
> It makes perfect sense. Why have to set another permission for someone when you can just set them as mod and it deals with noclip already.

We can incorporate that in the mod group

**Comment by t0retto** [comment]
you cannot use txAdmin events without its own permissions (not ace perms) unless you modify them which makes the suggestion a bit useless and not doable if you want a standalone resource.

for reference this is the current txAdmin noclip code:

```lua
-- NoClip toggle keybind
RegisterCommand('txAdmin:menu:noClipToggle', function()
    if not menuIsAccessible then return end
    if not DoesPlayerHavePerm(menuPermissions, 'players.playermode') then
        return sendSnackbarMessage('error', 'nui_menu.misc.no_perms', true)
    end
    askChangePlayerMode(noClipEnabled and 'none' or 'noclip')
end)

```

**Comment by MafewTM** [comment]
We should just maintain our own version of noclip

**Pull request closed without merging**
